### PR TITLE
Added GIT_DOMAIN env variable to override default domain

### LINKED ISSUE #132: Allow override git domain
The git server's url is hardcoded to `github.com` (see [source](https://github.com/crazy-max/ghaction-github-pages/blob/dev/src/main.ts#L38)) which is fine for github usage however it would be cool to have possibility to override this default value via e.g. env variable `GIT_DOMAIN`.
This would makes the script even more universal and could be used for private's git servers.

### PR DESCRIPTION
**Pull request by lkrzyzanek**
fixes #132

### CODE REVIEW

**Review by crazy-max — CHANGES_REQUESTED** [review]
@lkrzyzanek Thanks for your contrib. Please read the [contribution notes](https://github.com/crazy-max/ghaction-github-pages/blob/dev/.github/CONTRIBUTING.md#submitting-a-pull-request) (missing `yarn run pre-checkin)`.

**Comment by lkrzyzanek** [comment]
Thanks for review. I run `yarn run pre-checkin` and commit changes again.

**Review by crazy-max — APPROVED** [review]
LGTM thanks for your contrib. I think I will do a small change to use action input instead of an env var. Keep you in touch in a follow-up PR.

**Comment by lkrzyzanek** [comment]
Cool. Thanks a lot!

**Pull request merged**
