### PR TITLE
Customization for commit message, committer name/email

### PR DESCRIPTION
**Pull request by sergeyzwezdin**
#8

### CODE REVIEW

**Comment by crazy-max** [comment]
Hi @sergeyzwezdin, thanks for your contrib. Can you run `npm run build && npm run format && npm prune --production` and push your changes before I check your PR please?
More info on [CONTRIBUTING.md](https://github.com/crazy-max/ghaction-github-pages/blob/master/.github/CONTRIBUTING.md)

**Comment by sergeyzwezdin** [comment]
@crazy-max done

**Comment by sergeyzwezdin** [comment]
Added

**Comment by sergeyzwezdin** [comment]
@crazy-max Are you going to assign a version for this? It is not so convenient to use commit hash in CI setup :D

**Comment by crazy-max** [comment]
@sergeyzwezdin Done :)
See https://github.com/crazy-max/ghaction-github-pages/releases/tag/v1.1.0

**Pull request merged**
